
package com.actualite.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ActualiteService", targetNamespace = "http://localhost/news-platform-php/backend/api/soap_server.php", wsdlLocation = "http://localhost/news-platform-php/backend/api/soap_server.php?wsdl")
public class ActualiteService
    extends Service
{

    private final static URL ACTUALITESERVICE_WSDL_LOCATION;
    private final static WebServiceException ACTUALITESERVICE_EXCEPTION;
    private final static QName ACTUALITESERVICE_QNAME = new QName("http://localhost/news-platform-php/backend/api/soap_server.php", "ActualiteService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost/news-platform-php/backend/api/soap_server.php?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ACTUALITESERVICE_WSDL_LOCATION = url;
        ACTUALITESERVICE_EXCEPTION = e;
    }

    public ActualiteService() {
        super(__getWsdlLocation(), ACTUALITESERVICE_QNAME);
    }

    public ActualiteService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ACTUALITESERVICE_QNAME, features);
    }

    public ActualiteService(URL wsdlLocation) {
        super(wsdlLocation, ACTUALITESERVICE_QNAME);
    }

    public ActualiteService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ACTUALITESERVICE_QNAME, features);
    }

    public ActualiteService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ActualiteService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ActualitePortType
     */
    @WebEndpoint(name = "ActualitePort")
    public ActualitePortType getActualitePort() {
        return super.getPort(new QName("http://localhost/news-platform-php/backend/api/soap_server.php", "ActualitePort"), ActualitePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ActualitePortType
     */
    @WebEndpoint(name = "ActualitePort")
    public ActualitePortType getActualitePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://localhost/news-platform-php/backend/api/soap_server.php", "ActualitePort"), ActualitePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ACTUALITESERVICE_EXCEPTION!= null) {
            throw ACTUALITESERVICE_EXCEPTION;
        }
        return ACTUALITESERVICE_WSDL_LOCATION;
    }

}
